### ISSUE TITLE
Error when running approved:review

### ISSUE THREAD

**Issue by ChristianConstantNel** [buttonsrtoys/approved#18]
Hi!

I think this is a very interesting package!
When I run dart run approved:review I get this error: Could not find file `approved:review`

Should I match my test file's name to something?

**Comment by buttonsrtoys** [comment]
> When I run dart run approved:review I get this error: 
>     "Could not find file approved:review"

Thanks for the supportive comments and for raising the issue! I suspect you calling "dart run approved:review" from a subfolder of your project. Maybe from within /test? Currently, you have to call "dart run approved:review" from your project's root folder. It would be handy if you could call review from a subfolder. I'll add this option to the projects roadmap.

**Comment by ChristianConstantNel** [comment]
Thanks for the reply! This worked!
